#!/bin/sh

if [[ -f "${HOME}/.dwm/config" ]]; then
    source "${HOME}/.dwm/config"
fi

if [[ -f "${background_image}" && `file -i "${background_image}" | cut -s -d ' ' -f 2` =~ ^image/* ]]; then
    feh --bg-scale "${background_image}" &
fi

if [[ -z "${show_battery}" || ! -f "${battery_device}/capacity" || ! -f "${adapter_device}/online" ]]; then
    show_battery=0
    battery_status=""
fi

glyph_clock=$(echo -e "\uf017")
glyph_sound=$(echo -e "\uf028")
glyph_weather=$(echo -e "\uf185")
glyph_glob=$(echo -e "\uf11c")
glyph_degree=$(echo -e "\u00b0")
glyph_battery=$(echo -e "\uf0e7")

while true
do

    if [[ ${show_battery} -eq 1 ]]; then
        battery_status="${glyph_battery} $(cat "${battery_device}/capacity")% `[[ $(cat "${adapter_device}/online") -eq 1 ]] && echo AC || echo DC`"
    fi

    if [ -f "/tmp/weather" ]; then
        weather="$(cat '/tmp/weather')${glyph_degree}"
    fi

    volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')%"

    if [ "$(xset -q | grep LED | awk '{ print $10 }' | cut -c5)" -eq 0 ]; then
        lang="En"
    else
        lang="Ru";
    fi

    xsetroot -name "${glyph_glob} ${lang}   ${glyph_weather} ${weather}   ${glyph_sound} ${volume}   ${battery_status}   ${glyph_clock} $(date +'%R')"
    sleep 0.5s
done &
